## Librerie

In [2]:
import numpy as np
import sys

## Caricamento

In [34]:
cliente_aggiuntivo = np.array(["Angelica", 11, 0.1134, 4], dtype="str")
pazienti_1 = np.loadtxt("pazienti_1.csv", delimiter = ',')
pazienti_1_nome = np.genfromtxt("pazienti_1_nome.csv", dtype="str")
pazienti_2 = np.load("pazienti_2.npy")
nomi = np.loadtxt("nomi.txt", dtype = 'str')
## Stampa completa
np.set_printoptions(threshold = sys.maxsize)

## Tipi

In [18]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full((2,5), 9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [25]:
np.full_like(pazienti_1, 9)

array([[9., 9.],
       [9., 9.],
       [9., 9.]])

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.random.randint(2, 5, size = (4))

array([2, 3, 2, 4])

In [31]:
np.random.rand(3,2,2)

array([[[0.7886904 , 0.70688501],
        [0.7079416 , 0.82206497]],

       [[0.61096416, 0.80595784],
        [0.88384713, 0.26593091]],

       [[0.61104026, 0.4620046 ],
        [0.4612884 , 0.32752312]]])

## Creazione pazienti 1

In [40]:
sensibilita = np.random.rand(pazienti_1.shape[0], 1)

In [45]:
pazienti_1_nome = pazienti_1_nome.reshape(3,1)

In [50]:
pazienti_1 = np.hstack([pazienti_1_nome, pazienti_1])

In [52]:
pazienti_1 = np.insert(pazienti_1, [2], sensibilita, axis = 1)

In [53]:
pazienti_1

array([['Maria,', '5.0', '0.5431546536265789', '3.0'],
       ['Rosanna,', '2.0', '0.43944708652005715', '6.0'],
       ['Giacopo', '1.0', '0.4857418605543232', '9.0']], dtype='<U32')

## Pazienti 2

In [87]:
## np.random.choice(nomi)
prima = np.array([[np.random.choice(nomi), np.random.randint(0,10)] for _ in range(3)])

In [88]:
pazienti_2 = np.hstack([prima, pazienti_2])

In [89]:
pazienti_2

array([['Ancilla', '7', '0.123', '9.0'],
       ['Dina', '7', '0.914', '3.0'],
       ['Vissia', '9', '0.401', '1.0']], dtype='<U32')

## Unione

In [94]:
pazienti = np.vstack([cliente_aggiuntivo, pazienti_1, pazienti_2])

In [95]:
pazienti

array([['Angelica', '11', '0.1134', '4'],
       ['Maria,', '5.0', '0.5431546536265789', '3.0'],
       ['Rosanna,', '2.0', '0.43944708652005715', '6.0'],
       ['Giacopo', '1.0', '0.4857418605543232', '9.0'],
       ['Ancilla', '7', '0.123', '9.0'],
       ['Dina', '7', '0.914', '3.0'],
       ['Vissia', '9', '0.401', '1.0']], dtype='<U32')

## Indexing

In [96]:
pazienti

array([['Angelica', '11', '0.1134', '4'],
       ['Maria,', '5.0', '0.5431546536265789', '3.0'],
       ['Rosanna,', '2.0', '0.43944708652005715', '6.0'],
       ['Giacopo', '1.0', '0.4857418605543232', '9.0'],
       ['Ancilla', '7', '0.123', '9.0'],
       ['Dina', '7', '0.914', '3.0'],
       ['Vissia', '9', '0.401', '1.0']], dtype='<U32')

In [99]:
pazienti[0, 0]

'Angelica'

In [100]:
pazienti[:, 0]

array(['Angelica', 'Maria,', 'Rosanna,', 'Giacopo', 'Ancilla', 'Dina',
       'Vissia'], dtype='<U32')

In [103]:
pazienti[:, 1 : -1]

array([['11', '0.1134'],
       ['5.0', '0.5431546536265789'],
       ['2.0', '0.43944708652005715'],
       ['1.0', '0.4857418605543232'],
       ['7', '0.123'],
       ['7', '0.914'],
       ['9', '0.401']], dtype='<U32')

In [104]:
prova = np.array([1,2,3,4,5])

In [105]:
prova

array([1, 2, 3, 4, 5])

In [106]:
prova += 1

In [107]:
prova

array([2, 3, 4, 5, 6])

In [108]:
np.cos(prova)

array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [109]:
prova[ prova % 2 == 0]

array([2, 4, 6])

In [117]:
~(prova > 3) & (prova < 6)

array([ True,  True, False, False, False])

## Somma

In [118]:
somma = pazienti_1[:, -1].astype(float) + pazienti_2[:, -1].astype(float)

In [119]:
somma

array([12.,  9., 10.])

In [120]:
somma.sum()

31.0

## Esercizio

In [121]:
array_rg = np.arange(0,49).reshape(7,7)

In [129]:
copia = np.copy(array_rg)

In [136]:
copia[2 : -2, [1,-2]] = 0

In [137]:
copia

array([[100,   1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12,  13],
       [ 14,   0,  16,  17,  18,   0,  20],
       [ 21,   0,  23,  24,  25,   0,  27],
       [ 28,   0,  30,  31,  32,   0,  34],
       [ 35,  36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47,  48]])

In [138]:
copia[[1, -2], 1 : -1] = 0

In [139]:
copia

array([[100,   1,   2,   3,   4,   5,   6],
       [  7,   0,   0,   0,   0,   0,  13],
       [ 14,   0,  16,  17,  18,   0,  20],
       [ 21,   0,  23,  24,  25,   0,  27],
       [ 28,   0,  30,  31,  32,   0,  34],
       [ 35,   0,   0,   0,   0,   0,  41],
       [ 42,  43,  44,  45,  46,  47,  48]])

In [140]:
copia[int(copia.shape[0]/ 2) , int(copia.shape[0] / 2)] = 0

In [141]:
copia

array([[100,   1,   2,   3,   4,   5,   6],
       [  7,   0,   0,   0,   0,   0,  13],
       [ 14,   0,  16,  17,  18,   0,  20],
       [ 21,   0,  23,   0,  25,   0,  27],
       [ 28,   0,  30,  31,  32,   0,  34],
       [ 35,   0,   0,   0,   0,   0,  41],
       [ 42,  43,  44,  45,  46,  47,  48]])