## Librerie

In [74]:
import numpy as np
import sys

## Caricamento

In [75]:
## Inizializzazione con dati scelti dal programmatore
cliente_aggiuntivo = np.array(["Angelica", 11, 0.1134, 4], dtype="str")
## Caricamento pazienti_1 con loadtxt
pazienti_1 = np.loadtxt("pazienti_1.csv", delimiter = ',')
## Caricamento dei nomi dei pazienti_1 tramite genfromtxt
pazienti_1_nome = np.genfromtxt("pazienti_1_nome.csv", dtype="str")
## Caricamento da file npy
pazienti_2 = np.load("pazienti_2.npy")
## Caricamento da file di testo
nomi = np.loadtxt("nomi.txt", dtype = 'str')
## Stampa completa
np.set_printoptions(threshold = sys.maxsize)

## Tipi

In [76]:
## Zeri
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [77]:
## Uno
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
## Shape di un altra variabile
np.full_like(pazienti_1, 9)

array([[9., 9.],
       [9., 9.],
       [9., 9.]])

In [79]:
## Scala da 0 a 10 (non compreso)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
## Numeri Randomici interi
np.random.randint(2, 5, size = (4))

array([2, 3, 4, 4])

In [81]:
## Numeri randomici float
np.random.rand(3,2,2)

array([[[0.24703155, 0.14927494],
        [0.7920084 , 0.55657565]],

       [[0.71198687, 0.63837642],
        [0.26674248, 0.06100644]],

       [[0.93546054, 0.27001669],
        [0.29025654, 0.89722946]]])

## Creazione pazienti 1

In [82]:
## Creazione della sensibilità (float)
sensibilita = np.random.rand(pazienti_1.shape[0], 1)

In [83]:
## Imposto pazienti_1_nome per essere compatibile con pazienti_1
pazienti_1_nome = pazienti_1_nome.reshape(3,1)

In [84]:
## Aggiunto pazienti_1_nome
pazienti_1 = np.hstack([pazienti_1_nome, pazienti_1])

In [85]:
## Aggiungo la sensibilità alla penultima posizione
pazienti_1 = np.insert(pazienti_1, [2], sensibilita, axis = 1)

In [86]:
## Stampo
pazienti_1

array([['Maria,', '5.0', '0.8483012639358164', '3.0'],
       ['Rosanna,', '2.0', '0.7731361527340781', '6.0'],
       ['Giacopo', '1.0', '0.35428132586074557', '9.0']], dtype='<U32')

## Pazienti 2

In [87]:
'''
    Creo un array con 3 righe e 2 colonne dove
    la prima colonna contiene dei nomi casuali
    la seconda colonna un numero randomico intero
'''
prima = np.array([[np.random.choice(nomi), np.random.randint(0,10)] for _ in range(3)])

In [88]:
## Aggiungo tutto a pazienti_2
pazienti_2 = np.hstack([prima, pazienti_2])

In [89]:
## Stampo
pazienti_2

array([['Rahda', '4', '0.123', '9.0'],
       ['Linnea', '4', '0.914', '3.0'],
       ['Naomi', '5', '0.401', '1.0']], dtype='<U32')

## Unione

In [90]:
'''
    Unisco tutto per far sì che si ottenga un array con la seguente impostazione:
    cliente_aggiuntivo
    pazienti_1
    pazienti_2
'''
pazienti = np.vstack([cliente_aggiuntivo, pazienti_1, pazienti_2])

## Indexing

In [91]:
## Stampa
pazienti

array([['Angelica', '11', '0.1134', '4'],
       ['Maria,', '5.0', '0.8483012639358164', '3.0'],
       ['Rosanna,', '2.0', '0.7731361527340781', '6.0'],
       ['Giacopo', '1.0', '0.35428132586074557', '9.0'],
       ['Rahda', '4', '0.123', '9.0'],
       ['Linnea', '4', '0.914', '3.0'],
       ['Naomi', '5', '0.401', '1.0']], dtype='<U32')

In [92]:
## Prendo il valore alla colonna n^0 e alla riga n^0
pazienti[0, 0]

'Angelica'

In [93]:
## prendo i valori di tutte le righe alla colonna n^0
pazienti[:, 0]

array(['Angelica', 'Maria,', 'Rosanna,', 'Giacopo', 'Rahda', 'Linnea',
       'Naomi'], dtype='<U32')

In [94]:
## Prendo i valori di tutte le righe però delle colonne centrali
pazienti[:, 1 : -1]

array([['11', '0.1134'],
       ['5.0', '0.8483012639358164'],
       ['2.0', '0.7731361527340781'],
       ['1.0', '0.35428132586074557'],
       ['4', '0.123'],
       ['4', '0.914'],
       ['5', '0.401']], dtype='<U32')

In [95]:
## Inizializzo array
prova = np.array([1,2,3,4,5])

In [96]:
## Stampo
prova

array([1, 2, 3, 4, 5])

In [97]:
## Aggiungo 1 a tutti i valori
prova + 1

array([2, 3, 4, 5, 6])

In [98]:
## Faccio il coseno di tutti i valori
np.cos(prova)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [99]:
## Prendo tutti i valori pari
prova[ prova % 2 == 0]

array([2, 4])

In [100]:
## Prendo tutti i valori che sono minori uguali a 3
e maggiori uguali a 6
~(prova > 3) & (prova < 6)

SyntaxError: invalid syntax (<ipython-input-100-80c82fe887c1>, line 2)

## Somma

In [101]:
'''
    Prendo, della variabile pazienti_1 e pazienti_2, 
    l'ultima colonna di tutte le righe.
    Le trasformo in float siccome sono delle stringhe e poi sommo
    tutte le righe fra le due colonne
'''
somma = pazienti_1[:, -1].astype(float) + pazienti_2[:, -1].astype(float)

In [102]:
## Stampa
somma

array([12.,  9., 10.])

In [103]:
## Faccio la somma di tutti i valori dell'array
somma.sum()

31.0

## Esercizio

In [104]:
## Cercare di riprodurre l'immagine Esercizio.png utilizzando
## Le funzioni numpy

In [105]:
## Creo array con i numeri da 0 a 49 (non compreso) e lo rendo un 7*7
array_rg = np.arange(0,49).reshape(7,7)

In [106]:
## Ne creo una copia dove ci lavoreremo
copia = np.copy(array_rg)

In [107]:
## Rendi 0 le righe centrali con un padding di 2
## Dall'alto e dal basso e con un padding orrizontale di 1
copia[2 : -2, [1,-2]] = 0

In [108]:
##Stampa
copia

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14,  0, 16, 17, 18,  0, 20],
       [21,  0, 23, 24, 25,  0, 27],
       [28,  0, 30, 31, 32,  0, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [109]:
## Rendo 0 i valori della riga n^1 e della penultima riga
## Con uno spazio verticale di 1
copia[[1, -2], 1 : -1] = 0

In [110]:
## Stampa
copia

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  0,  0,  0,  0,  0, 13],
       [14,  0, 16, 17, 18,  0, 20],
       [21,  0, 23, 24, 25,  0, 27],
       [28,  0, 30, 31, 32,  0, 34],
       [35,  0,  0,  0,  0,  0, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [111]:
## Prendo il centro e lo rendo 0
copia[int(copia.shape[0]/ 2) , int(copia.shape[0] / 2)] = 0

In [112]:
## Stampa
copia

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  0,  0,  0,  0,  0, 13],
       [14,  0, 16, 17, 18,  0, 20],
       [21,  0, 23,  0, 25,  0, 27],
       [28,  0, 30, 31, 32,  0, 34],
       [35,  0,  0,  0,  0,  0, 41],
       [42, 43, 44, 45, 46, 47, 48]])